const fs = require('fs');
const path = require('path');

const ARTIFACTS_DIR = path.join(__dirname, '../../contracts/artifacts/contracts');
const OUTPUT_FILE = path.join(__dirname, '../lib/contracts/abis.ts');

const contractFiles = [
  { name: 'ASSET_FACTORY_ABI', path: 'AssetFactory.sol/AssetFactory.json' },
  { name: 'ASSET_TOKEN_ABI', path: 'AssetToken.sol/AssetToken.json' },
  { name: 'ASSET_MARKETPLACE_ABI', path: 'AssetMarketplace.sol/AssetMarketplace.json' },
  { name: 'ASSET_REGISTRY_ABI', path: 'AssetRegistry.sol/AssetRegistry.json' },
  { name: 'ASSET_GOVERNANCE_ABI', path: 'AssetGovernance.sol/AssetGovernance.json' },
  { name: 'KYC_REGISTRY_ABI', path: 'fhe/FHEKYCRegistry.sol/FHEKYCRegistry.json' },
  { name: 'FHE_VALUATION_ABI', path: 'fhe/FHEAssetValuation.sol/FHEAssetValuation.json' },
  { name: 'FHE_FEE_MANAGER_ABI', path: 'fhe/FHEFeeManager.sol/FHEFeeManager.json' },
  { name: 'CONFIDENTIAL_LOAN_ABI', path: 'fhe/ConfidentialLoan.sol/ConfidentialLoan.json' },
  { name: 'MODULAR_COMPLIANCE_ABI', path: '../@tokenysolutions/t-rex/contracts/compliance/modular/ModularCompliance.sol/ModularCompliance.json' },
  { name: 'KYC_COMPLIANCE_MODULE_ABI', path: 'KYCComplianceModule.sol/KYCComplianceModule.json' }
];

let output = '// This file is auto-generated by extract-abis.js\n\n';

contractFiles.forEach(cf => {
  const fullPath = path.join(ARTIFACTS_DIR, cf.path);
  if (fs.existsSync(fullPath)) {
    const artifact = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
    output += `export const ${cf.name} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
    console.log(`Extracted ${cf.name}`);
  } else {
    console.error(`Missing artifact: ${fullPath}`);
  }
});

// Add Mock USDC ABI (minimal)
output += `export const USDC_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function transfer(address, uint256) returns (bool)",
  "function allowance(address, address) view returns (uint256)",
  "function approve(address, uint256) returns (bool)",
  "function transferFrom(address, address, uint256) returns (bool)",
  "function faucet() returns (bool)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)"
] as const;\n`;

fs.writeFileSync(OUTPUT_FILE, output);
console.log(`Successfully wrote ${OUTPUT_FILE}`);
