import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'How It Works | AssetsGrator',
  description: 'Step-by-step guide to investing in tokenised real-world assets on AssetsGrator — from KYC to on-chain distributions.',
};

const STEPS = [
  {
    n: '01',
    title: 'Complete Identity Verification',
    icon: '🪪',
    color: '#6366f1',
    bg: '#eef2ff',
    content: [
      'Create an account and connect your Ethereum-compatible wallet (Arbitrum network).',
      'Submit your government-issued ID and proof of address via our KYC partner, Sumsub. The process typically takes under 10 minutes.',
      'Confirm your investor classification (Sophisticated Investor, High Net Worth Individual, or Professional Investor) as defined by FCA COBS rules.',
    ],
    note: 'Your identity data is processed by Sumsub under a GDPR-compliant Data Processing Agreement. We do not store raw ID documents — only the verified status.',
  },
  {
    n: '02',
    title: 'Get Approved & Whitelisted',
    icon: '✅',
    color: '#0ea5e9',
    bg: '#e0f2fe',
    content: [
      'Our compliance team reviews your application against UK investor classification requirements and AML checks.',
      'Approval typically takes 24–48 hours.',
      'Once approved, your wallet address is whitelisted on-chain via the ERC-3643 (T-REX) compliance module.',
      'Your KYC verification status is registered on-chain in the IdentityRegistry contract, allowing compliant interactions.',
    ],
    note: 'Whitelisting is wallet-specific. If you change your wallet, you must re-apply.',
  },
  {
    n: '03',
    title: 'Browse & Select Assets',
    icon: '🔍',
    color: '#10b981',
    bg: '#d1fae5',
    content: [
      'Browse the asset marketplace — each listing displays the asset name, location, asset class, total valuation (public), expected yield, and token price.',
      'Total asset valuations are published transparently on-chain via our AssetValuation contract, updated by authorised valuators.',
      'Review the off-chain legal documentation: title deeds, generation licences, or VCS/RECS certifications for each asset.',
      'Fee ranges are publicly visible (1–3%). The exact per-asset fee rate is managed by our FeeManager smart contract.',
    ],
    note: 'Each asset has a minimum investment amount. Assets are listed in GBPT.',
  },
  {
    n: '04',
    title: 'Invest and Receive Tokens',
    icon: '🪙',
    color: '#f59e0b',
    bg: '#fef3c7',
    content: [
      'Fund your wallet with GBPT on Arbitrum and initiate your investment.',
      'Smart contracts verify your whitelist status in real-time before processing the transaction.',
      'ERC-3643 Asset Tokens are minted directly to your wallet — each token represents a verified fractional ownership share.',
      'Your token balance is recorded on the public ledger associated with your wallet address.',
    ],
    note: 'Token transfers are restricted to other whitelisted wallets via the T-REX compliance module. You cannot send tokens to a non-approved address.',
  },
  {
    n: '05',
    title: 'Participate in Governance',
    icon: '🗳️',
    color: '#8b5cf6',
    bg: '#ede9fe',
    content: [
      'As a co-owner, you can vote on material asset decisions — major capital works, refinancing events, or asset disposal proposals.',
      'Voting weight is proportional to your verified token holdings.',
      'Governance proposals are submitted and resolved on-chain with full auditability.',
    ],
    note: 'Governance is in development. Initially, material decisions will be managed by AssetsGrator with investor consultation.',
  },
  {
    n: '06',
    title: 'Receive Revenue Distributions',
    icon: '💷',
    color: '#2d6be4',
    bg: '#dbeafe',
    content: [
      'Revenue generated by underlying assets (rental income, energy tariffs, carbon credit proceeds) is collected and distributed on-chain.',
      'Distributions are made in GBPT, proportional to your verified token holdings.',
      'Platform fees — capped at 1–3% and managed transparently by the FeeManager contract — are deducted at distribution.',
      'Distributions are paid directly to your connected wallet, without intermediaries.',
    ],
    note: 'Distribution frequency varies by asset type (monthly for rent, quarterly for energy tariffs, annually for carbon credits).',
  },
];

const FAQS = [
  {
    q: 'What is the minimum investment?',
    a: 'Minimum investments vary by asset, typically starting at £500–£2,000 in GBPT. Each asset listing displays the token price and minimum ticket.',
  },
  {
    q: 'Can I sell my tokens?',
    a: 'Asset Tokens can be transferred to other whitelisted investors only. There is no public exchange listing. Liquidity depends on finding a willing buyer among the whitelisted investor base. We are working on a peer-to-peer transfer marketplace for verified holders.',
  },
  {
    q: 'Is my portfolio visible on the blockchain?',
    a: 'Yes, your token balances and transfers are recorded publicly on the Arbitrum blockchain, as is standard for public ledger transactions. However, your personal identity documents are stored securely off-chain and are never published on-chain.',
  },
  {
    q: 'What networks do I need?',
    a: 'AssetsGrator operates on the Arbitrum network (Ethereum Layer 2). You will need a compatible wallet (e.g. MetaMask, Rabby) configured for Arbitrum, and GBPT on Arbitrum to invest.',
  },
  {
    q: 'Is the platform regulated?',
    a: 'AssetsGrator currently operates within the FCA Regulatory Sandbox — a controlled testing environment overseen by the UK Financial Conduct Authority. Full FCA authorisation is pending. We are not yet authorised under FSMA 2000.',
  },
  {
    q: 'What happens to my investment if AssetsGrator closes?',
    a: 'Your token holdings represent a claim on legally documented real-world assets. Off-chain legal instruments (title deeds, licences) are structured to allow enforcement independent of the platform. We maintain a legal contingency structure specifically for this scenario.',
  },
];

export default function HowItWorksPage() {
  return (
    <main style={{ background: 'var(--bg)', minHeight: '100vh', paddingBottom: '5rem' }}>
      {/* Hero */}
      <section style={{ background: 'linear-gradient(135deg, #0f0a2e 0%, #1a3a6b 100%)', padding: 'clamp(3.5rem, 8vw, 6rem) 1.25rem', textAlign: 'center' }}>
        <div className="container" style={{ maxWidth: 700 }}>
          <p style={{ fontSize: 12, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#a5b4fc', marginBottom: 12 }}>Getting Started</p>
          <h1 style={{ fontSize: 'clamp(2rem, 5vw, 3rem)', fontWeight: 900, color: '#fff', lineHeight: 1.2, marginBottom: 16 }}>How It Works</h1>
          <p style={{ fontSize: 16, color: 'rgba(255,255,255,0.65)', lineHeight: 1.8 }}>
            From identity verification to on-chain distributions — a complete walkthrough of the AssetsGrator investment journey.
          </p>
        </div>
      </section>

      {/* Steps */}
      <section className="section-pad">
        <div className="container" style={{ maxWidth: 860 }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
            {STEPS.map((step, i) => (
              <div key={step.n} style={{ display: 'flex', gap: '1.5rem', alignItems: 'flex-start' }}>
                {/* Step number line */}
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', flexShrink: 0 }}>
                  <div style={{
                    width: 52, height: 52, borderRadius: '50%',
                    background: step.bg, border: `2px solid ${step.color}44`,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontSize: '1.3rem',
                  }}>
                    {step.icon}
                  </div>
                  {i < STEPS.length - 1 && (
                    <div style={{ width: 2, flex: 1, minHeight: 40, background: 'var(--border)', marginTop: 8 }} />
                  )}
                </div>

                {/* Content */}
                <div style={{ background: 'var(--white)', border: '1px solid var(--border)', borderLeft: `4px solid ${step.color}`, borderRadius: 14, padding: '1.5rem', flex: 1, marginBottom: i < STEPS.length - 1 ? '0.5rem' : 0 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
                    <span style={{ fontSize: 11, fontWeight: 700, color: step.color, letterSpacing: '0.06em' }}>STEP {step.n}</span>
                  </div>
                  <h2 style={{ fontSize: 18, fontWeight: 800, color: '#111827', marginBottom: 14 }}>{step.title}</h2>
                  <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {step.content.map((point, j) => (
                      <li key={j} style={{ display: 'flex', gap: 10, alignItems: 'flex-start', fontSize: 14, color: '#374151', lineHeight: 1.7 }}>
                        <span style={{ color: step.color, flexShrink: 0, marginTop: 2 }}>▸</span>
                        {point}
                      </li>
                    ))}
                  </ul>
                  {step.note && (
                    <div style={{ marginTop: 12, padding: '0.75rem 1rem', background: `${step.color}0d`, borderRadius: 8, fontSize: 12, color: step.color, fontWeight: 600 }}>
                      ℹ️ {step.note}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="section-pad" style={{ background: 'var(--white)' }}>
        <div className="container" style={{ maxWidth: 800 }}>
          <p style={{ fontSize: 12, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--brand)', marginBottom: 8 }}>Questions</p>
          <h2 style={{ fontSize: 'clamp(1.4rem, 3vw, 2rem)', fontWeight: 800, color: '#111827', marginBottom: '2rem' }}>Frequently Asked Questions</h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {FAQS.map((faq) => (
              <div key={faq.q} style={{ border: '1px solid var(--border)', borderRadius: 12, padding: '1.25rem 1.5rem', background: 'var(--bg)' }}>
                <p style={{ fontWeight: 700, fontSize: 15, color: '#111827', marginBottom: 8 }}>{faq.q}</p>
                <p style={{ fontSize: 14, color: '#374151', lineHeight: 1.75, margin: 0 }}>{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="section-pad" style={{ background: 'linear-gradient(135deg, #0f0a2e, #1e1b4b)', textAlign: 'center' }}>
        <div className="container" style={{ maxWidth: 540 }}>
          <h2 style={{ fontSize: 'clamp(1.4rem, 3vw, 1.9rem)', fontWeight: 800, color: '#fff', marginBottom: 12 }}>Ready to begin?</h2>
          <p style={{ fontSize: 15, color: 'rgba(255,255,255,0.6)', marginBottom: '2rem' }}>
            Start with identity verification — approval takes under 48 hours.
          </p>
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link href="/kyc">
              <button className="btn btn-primary btn-lg">Start KYC Verification</button>
            </Link>
            <Link href="/legal/risk-disclosure">
              <button className="btn btn-outline btn-lg" style={{ color: '#fff', borderColor: 'rgba(255,255,255,0.3)', background: 'rgba(255,255,255,0.07)' }}>
                Read Risk Disclosure
              </button>
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
